"""Restyles the tabletops in real-to-sim.usd:

1. Authors primvars:st (vertex interpolation) on /World/Table/TableTop and
   /World/Table_02/TableTop -- both are already UsdGeomMesh (a 72-point
   rounded-rectangle extrusion: 24 bottom verts, 24 bevel verts, 24 top-face
   verts; 48 side quads + 2 n-gon caps), just without UVs. st is a planar
   projection of each point's local (x, y) onto its own mesh-local bbox:
     s = (x - minX) / (maxX - minX)
     t = (y - minY) / (maxY - minY)
   so t=1 sits at the tabletop's +Y edge, t=0 at its -Y edge (see
   gen_table_textures.py docstring for how this lines up with the generated
   image's rows).
2. Wires the shared /World/Looks/Laminate material's UsdPreviewSurface up to
   the new table_diffuse.png / table_roughness.png / table_normal.png
   texture set (generated by gen_table_textures.py) through a shared primvar
   reader. Laminate is already bound to both TableTop prims, so this single
   edit covers both tables. No prims are added/removed/moved; no geometry,
   transforms, or other materials are touched.

Run with Isaac Sim's own Python (needs pxr, which only resolves once the kit
app has bootstrapped extensions):
    C:\\Isaac-Sim\\python.bat usd-composer-stages\\apply_table_material.py
"""
from isaacsim import SimulationApp

simulation_app = SimulationApp({"headless": True})

from pxr import Gf, Sdf, Usd, UsdGeom, UsdShade, Vt

STAGE_PATH = (
    r"c:\Users\OMNI-User\Desktop\Sim-to-Real-SO-101-Workshop\source"
    r"\sim_to_real_so101\demo\real-to-sim.usd"
)

stage = Usd.Stage.Open(STAGE_PATH)
assert stage, f"Failed to open {STAGE_PATH}"

# ---------------------------------------------------------------------------
# 1. TableTop UVs: planar (x, y) projection per mesh, vertex-interpolated
# ---------------------------------------------------------------------------
for table_name in ["Table", "Table_02"]:
    top_prim = stage.GetPrimAtPath(f"/World/{table_name}/TableTop")
    assert top_prim.IsValid(), f"/World/{table_name}/TableTop not found"
    assert top_prim.GetTypeName() == "Mesh", f"expected Mesh, got {top_prim.GetTypeName()}"

    mesh = UsdGeom.Mesh(top_prim)
    points = mesh.GetPointsAttr().Get()
    assert points, f"{table_name}/TableTop has no points"

    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    min_x, max_x = min(xs), max(xs)
    min_y, max_y = min(ys), max(ys)

    st_values = Vt.Vec2fArray(
        [
            Gf.Vec2f(
                (p[0] - min_x) / (max_x - min_x),
                (p[1] - min_y) / (max_y - min_y),
            )
            for p in points
        ]
    )

    st_primvar = UsdGeom.PrimvarsAPI(top_prim).CreatePrimvar(
        "st", Sdf.ValueTypeNames.TexCoord2fArray, UsdGeom.Tokens.vertex
    )
    st_primvar.Set(st_values)
    print(f"{table_name}/TableTop: authored {len(st_values)} st values "
          f"(x range {min_x:.3f}..{max_x:.3f}, y range {min_y:.3f}..{max_y:.3f})")

# ---------------------------------------------------------------------------
# 2. Material: wire UsdPreviewSurface to the new texture set
# ---------------------------------------------------------------------------
material_path = "/World/Looks/Laminate"
shader_path = "/World/Looks/Laminate/Shader"
material_prim = stage.GetPrimAtPath(material_path)
shader_prim = stage.GetPrimAtPath(shader_path)
assert material_prim.IsValid() and shader_prim.IsValid()

shader = UsdShade.Shader(shader_prim)
material = UsdShade.Material(material_prim)

reader_prim = stage.DefinePrim(f"{material_path}/stReader", "Shader")
reader = UsdShade.Shader(reader_prim)
reader.CreateIdAttr("UsdPrimvarReader_float2")
reader.CreateInput("varname", Sdf.ValueTypeNames.Token).Set("st")
reader.CreateInput("fallback", Sdf.ValueTypeNames.Float2).Set(Gf.Vec2f(0, 0))
reader_output = reader.CreateOutput("result", Sdf.ValueTypeNames.Float2)


def make_texture(name, file_rel_path, source_color_space, wrap="clamp"):
    tex_prim = stage.DefinePrim(f"{material_path}/{name}", "Shader")
    tex = UsdShade.Shader(tex_prim)
    tex.CreateIdAttr("UsdUVTexture")
    tex.CreateInput("file", Sdf.ValueTypeNames.Asset).Set(file_rel_path)
    tex.CreateInput("sourceColorSpace", Sdf.ValueTypeNames.Token).Set(source_color_space)
    tex.CreateInput("wrapS", Sdf.ValueTypeNames.Token).Set(wrap)
    tex.CreateInput("wrapT", Sdf.ValueTypeNames.Token).Set(wrap)
    st_input = tex.CreateInput("st", Sdf.ValueTypeNames.Float2)
    st_input.ConnectToSource(reader_output)
    return tex


diffuse_tex = make_texture("DiffuseTexture", "./tex/table/table_diffuse.png", "sRGB")
diffuse_rgb_out = diffuse_tex.CreateOutput("rgb", Sdf.ValueTypeNames.Float3)

roughness_tex = make_texture("RoughnessTexture", "./tex/table/table_roughness.png", "raw")
roughness_r_out = roughness_tex.CreateOutput("r", Sdf.ValueTypeNames.Float)

normal_tex = make_texture("NormalTexture", "./tex/table/table_normal.png", "raw")
normal_tex.CreateInput("scale", Sdf.ValueTypeNames.Float4).Set(Gf.Vec4f(2, 2, 2, 1))
normal_tex.CreateInput("bias", Sdf.ValueTypeNames.Float4).Set(Gf.Vec4f(-1, -1, -1, 0))
normal_rgb_out = normal_tex.CreateOutput("rgb", Sdf.ValueTypeNames.Float3)

diffuse_input = shader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f)
diffuse_input.ConnectToSource(diffuse_rgb_out)

roughness_input = shader.CreateInput("roughness", Sdf.ValueTypeNames.Float)
roughness_input.ConnectToSource(roughness_r_out)

normal_input = shader.CreateInput("normal", Sdf.ValueTypeNames.Normal3f)
normal_input.ConnectToSource(normal_rgb_out)

shader.CreateInput("metallic", Sdf.ValueTypeNames.Float).Set(0.0)
shader.CreateInput("opacity", Sdf.ValueTypeNames.Float).Set(1.0)

print("Material graph wired: stReader -> {Diffuse,Roughness,Normal}Texture -> Laminate/Shader")

stage.Save()
print("Saved", STAGE_PATH)

simulation_app.close()
