"""Restyles the demo floor in real-to-sim.usd:

1. Converts /World/Floor from an implicit UsdGeomCube (no UVs possible) to an
   explicit UsdGeomMesh box with the SAME size/position, but with authored
   primvars:st so a texture can be applied. subdivisionScheme is left "none"
   (flat quads) -- Catmull-Clark + creases misbehaves in Kit's RTX delegate
   on this machine, per prior local verification.
2. Wires /World/Looks/Floor's UsdPreviewSurface up to the new
   floor_diffuse.png / floor_roughness.png / floor_normal.png texture set
   (generated by gen_floor_textures.py) through a shared primvar reader.

Run with Isaac Sim's own Python (needs pxr, which only resolves once the kit
app has bootstrapped extensions):
    C:\\Isaac-Sim\\python.bat usd-composer-stages\\apply_floor_material.py
"""
from isaacsim import SimulationApp

simulation_app = SimulationApp({"headless": True})

from pxr import Gf, Sdf, Usd, UsdGeom, UsdShade, Vt

STAGE_PATH = (
    r"c:\Users\OMNI-User\Desktop\Sim-to-Real-SO-101-Workshop\source"
    r"\sim_to_real_so101\demo\real-to-sim.usd"
)

stage = Usd.Stage.Open(STAGE_PATH)
assert stage, f"Failed to open {STAGE_PATH}"

# ---------------------------------------------------------------------------
# 1. Floor: Cube -> Mesh with real UVs
# ---------------------------------------------------------------------------
floor_prim = stage.GetPrimAtPath("/World/Floor")
assert floor_prim.IsValid(), "/World/Floor not found"
assert floor_prim.GetTypeName() == "Cube", f"expected Cube, got {floor_prim.GetTypeName()}"

# preserve the existing xformOp:translate / xformOp:scale authored on the prim
xf_translate = floor_prim.GetAttribute("xformOp:translate").Get()
xf_scale = floor_prim.GetAttribute("xformOp:scale").Get()
print("Existing translate:", xf_translate, "scale:", xf_scale)

floor_prim.RemoveProperty("size")
floor_prim.SetTypeName("Mesh")
mesh = UsdGeom.Mesh(floor_prim)

h = 0.5
p0 = Gf.Vec3f(-h, -h, -h)
p1 = Gf.Vec3f(h, -h, -h)
p2 = Gf.Vec3f(h, h, -h)
p3 = Gf.Vec3f(-h, h, -h)
p4 = Gf.Vec3f(-h, -h, h)
p5 = Gf.Vec3f(h, -h, h)
p6 = Gf.Vec3f(h, h, h)
p7 = Gf.Vec3f(-h, h, h)
points = [p0, p1, p2, p3, p4, p5, p6, p7]

# faces: top(+Z, the visible floor surface), bottom(-Z), +X, -X, +Y, -Y
face_indices = [
    4, 5, 6, 7,  # +Z top
    0, 3, 2, 1,  # -Z bottom
    1, 2, 6, 5,  # +X
    3, 0, 4, 7,  # -X
    2, 3, 7, 6,  # +Y
    0, 1, 5, 4,  # -Y
]
face_counts = [4, 4, 4, 4, 4, 4]

normals = (
    [Gf.Vec3f(0, 0, 1)] * 4
    + [Gf.Vec3f(0, 0, -1)] * 4
    + [Gf.Vec3f(1, 0, 0)] * 4
    + [Gf.Vec3f(-1, 0, 0)] * 4
    + [Gf.Vec3f(0, 1, 0)] * 4
    + [Gf.Vec3f(0, -1, 0)] * 4
)

uv_quad = [Gf.Vec2f(0, 0), Gf.Vec2f(1, 0), Gf.Vec2f(1, 1), Gf.Vec2f(0, 1)]
st_values = uv_quad * 6  # top face is the important one (u=world X, v=world Y)

mesh.CreatePointsAttr(Vt.Vec3fArray(points))
mesh.CreateFaceVertexCountsAttr(Vt.IntArray(face_counts))
mesh.CreateFaceVertexIndicesAttr(Vt.IntArray(face_indices))
mesh.CreateExtentAttr(Vt.Vec3fArray([Gf.Vec3f(-h, -h, -h), Gf.Vec3f(h, h, h)]))
mesh.CreateSubdivisionSchemeAttr(UsdGeom.Tokens.none)
mesh.CreateDoubleSidedAttr(True)

normals_attr = mesh.CreateNormalsAttr(Vt.Vec3fArray(normals))
mesh.SetNormalsInterpolation(UsdGeom.Tokens.faceVarying)

st_primvar = UsdGeom.PrimvarsAPI(floor_prim).CreatePrimvar(
    "st", Sdf.ValueTypeNames.TexCoord2fArray, UsdGeom.Tokens.faceVarying
)
st_primvar.Set(Vt.Vec2fArray(st_values))

# re-author translate/scale exactly as before (SetTypeName preserves specs but be explicit/safe)
if xf_translate is not None:
    floor_prim.GetAttribute("xformOp:translate").Set(xf_translate)
if xf_scale is not None:
    floor_prim.GetAttribute("xformOp:scale").Set(xf_scale)

print("Floor converted to textured Mesh.")

# ---------------------------------------------------------------------------
# 2. Material: wire UsdPreviewSurface to the new texture set
# ---------------------------------------------------------------------------
material_path = "/World/Looks/Floor"
shader_path = "/World/Looks/Floor/Shader"
material_prim = stage.GetPrimAtPath(material_path)
shader_prim = stage.GetPrimAtPath(shader_path)
assert material_prim.IsValid() and shader_prim.IsValid()

shader = UsdShade.Shader(shader_prim)
material = UsdShade.Material(material_prim)

# shared primvar reader for "st"
reader_prim = stage.DefinePrim(f"{material_path}/stReader", "Shader")
reader = UsdShade.Shader(reader_prim)
reader.CreateIdAttr("UsdPrimvarReader_float2")
reader.CreateInput("varname", Sdf.ValueTypeNames.Token).Set("st")
reader.CreateInput("fallback", Sdf.ValueTypeNames.Float2).Set(Gf.Vec2f(0, 0))
reader_output = reader.CreateOutput("result", Sdf.ValueTypeNames.Float2)


def make_texture(name, file_rel_path, source_color_space, wrap="repeat"):
    tex_prim = stage.DefinePrim(f"{material_path}/{name}", "Shader")
    tex = UsdShade.Shader(tex_prim)
    tex.CreateIdAttr("UsdUVTexture")
    tex.CreateInput("file", Sdf.ValueTypeNames.Asset).Set(file_rel_path)
    tex.CreateInput("sourceColorSpace", Sdf.ValueTypeNames.Token).Set(source_color_space)
    tex.CreateInput("wrapS", Sdf.ValueTypeNames.Token).Set(wrap)
    tex.CreateInput("wrapT", Sdf.ValueTypeNames.Token).Set(wrap)
    st_input = tex.CreateInput("st", Sdf.ValueTypeNames.Float2)
    st_input.ConnectToSource(reader_output)
    return tex


diffuse_tex = make_texture("DiffuseTexture", "./tex/floor/floor_diffuse.png", "sRGB")
diffuse_rgb_out = diffuse_tex.CreateOutput("rgb", Sdf.ValueTypeNames.Float3)

roughness_tex = make_texture("RoughnessTexture", "./tex/floor/floor_roughness.png", "raw")
roughness_r_out = roughness_tex.CreateOutput("r", Sdf.ValueTypeNames.Float)

normal_tex = make_texture("NormalTexture", "./tex/floor/floor_normal.png", "raw")
normal_tex.CreateInput("scale", Sdf.ValueTypeNames.Float4).Set(Gf.Vec4f(2, 2, 2, 1))
normal_tex.CreateInput("bias", Sdf.ValueTypeNames.Float4).Set(Gf.Vec4f(-1, -1, -1, 0))
normal_rgb_out = normal_tex.CreateOutput("rgb", Sdf.ValueTypeNames.Float3)

diffuse_input = shader.CreateInput("diffuseColor", Sdf.ValueTypeNames.Color3f)
diffuse_input.ConnectToSource(diffuse_rgb_out)

roughness_input = shader.CreateInput("roughness", Sdf.ValueTypeNames.Float)
roughness_input.ConnectToSource(roughness_r_out)

normal_input = shader.CreateInput("normal", Sdf.ValueTypeNames.Normal3f)
normal_input.ConnectToSource(normal_rgb_out)

# satin, non-metallic
shader.CreateInput("metallic", Sdf.ValueTypeNames.Float).Set(0.0)

print("Material graph wired: stReader -> {Diffuse,Roughness,Normal}Texture -> Shader")

stage.Save()
print("Saved", STAGE_PATH)

simulation_app.close()
